number = set()

n1 = int(input("Enter no: "))
number.add(int(n1))
n2 = int(input("Enter no: "))
number.add(int(n2))
n3 = int(input("Enter no: "))
number.add(int(n3))
n4 = int(input("Enter no: "))
number.add(int(n4))
n5 = int(input("Enter no: "))
number.add(int(n5))
n6 = int(input("Enter no: "))
number.add(int(n6))
n7 = int(input("Enter no: "))
number.add(int(n7))
n8 = int(input("Enter no: "))
number.add(int(n8))

print(number)